### ISSUE TITLE
Form redirect if free_download == "No"

### ISSUE THREAD

**Issue by gordoncd** [thecodingaviator/coasttocow#26]
Functionality for form redirect to confirmation.php upon hitting submit and setting $metaSubmitted to true.

Additionally, need to implement identical changes to record_DO.php.

**Comment by gordoncd** [comment]
basically, the trigger for the button on the bottom needs to redirect the user to the update page which will tell the user that their data has been entered and sent or whatever they requested and notify them that an email was sent. 

we can't let them do this from the upload page since they would be submitting data without the metadata. 

need functionality for multiple files.

**Comment by thecodingaviator** [comment]
I'm completely lost right now. Let's sync my evening/your morning of the 13th.

**Comment by gordoncd** [comment]
this works now.
