### ISSUE TITLE
Figure out how to put files in a specific drive

### ISSUE THREAD

**Issue by thecodingaviator** [thecodingaviator/coasttocow#3]
Hi Gordon,

I got submit.php working but cannot put files in the right folder. Do you wanna work on this?

**Comment by gordoncd** [comment]
yes

I made some changes on the new branch submit_effort.  I think this will fix the problem but my local server isn't working right now so I need to fix that before I can test it.

**Comment by thecodingaviator** [comment]
Current progress on main:

![image](https://github.com/thecodingaviator/coasttocow/assets/34807532/4ed1f4c8-c1b4-401a-8934-1f51b7d86988)

**Comment by gordoncd** [comment]
Yeah this is where I was too. Need to check server environment next
probably?

**Comment by thecodingaviator** [comment]
I have an eerie suspicion that composer is not doing its job

**Comment by gordoncd** [comment]
composer doesn’t respond exist from ssh so I’d guess that’s the issue

**Comment by thecodingaviator** [comment]
![image](https://github.com/thecodingaviator/coasttocow/assets/34807532/1d735a09-82c2-4c9d-a3c1-05d57805ae96)

The vendor folder is there. How did you set composer up?

**Comment by gordoncd** [comment]
It was there when I synced there, but if you say in and call composer it
says not found¿ it didn’t get there from GitHub did it?

**Comment by thecodingaviator** [comment]
I may have put it there without knowing actually
