### ISSUE TITLE
Metadata submission doubled 

### ISSUE THREAD

**Issue by gordoncd** [thecodingaviator/coasttocow#30]
If user is uploding file in record_RD.php, the file will insert metadata, and then call upload.php which will also.  Need upload's info because includes file_id.  Basically we need upload to instead of making new row, to overwrite row with identical infomration, can potentially communicate where this is via $_SESSION variable (maybe unique_name).

**Comment by thecodingaviator** [comment]
@gordoncd are you working on this?

**Comment by gordoncd** [comment]
yeah. working on this today.

**Comment by gordoncd** [comment]
fixed.
