### ISSUE TITLE
form confirmation requires refresh after upload

### ISSUE THREAD

**Issue by gordoncd** [thecodingaviator/coasttocow#37]
after uploading file in record_RD, the redirect to confirmation page will only occur if user refreshes (runs php code again while $_SESSION['file_uploaded'] has been set).  

To fix we need to find a way to run the portion of the script that checks the status of the upload AFTER the upload has been handled by submit.js without refreshing the page.

**Comment by thecodingaviator** [comment]
I wonder if there's a way in JS to do this rather than use PHP

**Comment by gordoncd** [comment]
yeah. maybe we change the workflow as well. Having a popup from upload page and hiding the upload button would be a simpler solution
