### ISSUE TITLE
Reset Password Mailing Does Not Work

### ISSUE THREAD

**Issue by thecodingaviator** [thecodingaviator/coasttocow#57]
![image](https://github.com/thecodingaviator/coasttocow/assets/34807532/59cdd9cf-c0f9-4fda-9b39-6723f6c37222)

I can try figuring it out on Monday if you want. Signing off for the week

**Comment by thecodingaviator** [comment]
Actually, it looks like everything is a little bit messed up. Cannot login

![image](https://github.com/thecodingaviator/coasttocow/assets/34807532/0ef053b7-66c1-4341-8e4d-c407cd98b871)

**Comment by thecodingaviator** [comment]
Same on localhost:

![image](https://github.com/thecodingaviator/coasttocow/assets/34807532/dbef1fbc-8d7f-4e2d-b211-6d1870ce912b)

**Comment by gordoncd** [comment]
the mailer was broken, but the password was still changed which meant your password got changed and mail wasn't sent.  Probably should fix, but mail working now. Issue was that password wasn't available within function scope as it was being defined from the include statement.
If you use reset password again, youll get the email. (hopefully.)
